version: "3.9"

services:
  db:
    image: mariadb:10.11
    container_name: glpi_db
    environment:
      MYSQL_ROOT_PASSWORD: "glpi_root_password"
      MYSQL_DATABASE: "glpidb"
      MYSQL_USER: "glpi"
      MYSQL_PASSWORD: "glpi_password"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  glpi:
    image: diouxx/glpi:latest
    container_name: glpi_app
    depends_on:
      - db
    volumes:
      - glpi_app:/var/www/html
      - "/home/rattus/GLPI_complet/ansible/roles/glpi/files/plugins:/var/www/html/plugins"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glpi.rule=Host(`glpi.localhost`)"
      - "traefik.http.routers.glpi.entrypoints=websecure"
      - "traefik.http.routers.glpi.tls=true"
    restart: unless-stopped

volumes:
  db_data:
  glpi_app:

