glpi_db_name: "glpidb"
glpi_db_user: "glpi"
glpi_db_pass: "glpi_password"
glpi_db_root: "glpi_root_password"

zabbix_db_name: "zabbixdb"
zabbix_db_user: "zabbix"
zabbix_db_pass: "zabbix_password"
zabbix_db_root: "zabbix_root_password"
