version: "3.9"

services:

  zabbix-mysql:
    image: mariadb:10.11
    container_name: zabbix_mysql
    environment:
      MYSQL_ROOT_PASSWORD: zabbix_root
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - zbx_db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - glpi

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix_server
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    depends_on:
      - zabbix-mysql
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      - glpi

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix_web
    depends_on:
      - zabbix-server
      - zabbix-mysql
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      PHP_TZ: Europe/Paris
    restart: unless-stopped
    networks:
      - glpi

    labels:
      # Activation et règles Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.zabbix.rule=Host(`zabbix.localhost`)"
      - "traefik.http.routers.zabbix.entrypoints=websecure"
      - "traefik.http.routers.zabbix.tls=true"

      # Mapping Router → Service
      - "traefik.http.routers.zabbix.service=zabbix-web"

      # Service réel (nom du conteneur)
      - "traefik.http.services.zabbix-web.loadbalancer.server.port=8080"

networks:
  glpi:
    external: true

volumes:
  zbx_db:

